language: python
sudo : false

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=cover

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - repoze-checkins@lists.repoze.org
